name: flutter_tinder_swipe
description: A new Flutter plugin just like tinder swipe card , can do swipe left and right also have swipeable option by clicking  button
version: 0.0.3
homepage: https://github.com/SanchitSaran/flutter_tinder_swipe.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.fluttertinderswipe.flutter_tinder_swipe
        pluginClass: FlutterTinderSwipePlugin
      ios:
        pluginClass: FlutterTinderSwipePlugin
      macos:
        pluginClass: FlutterTinderSwipePlugin





